### ISSUE TITLE
Serverless Architecture Security  Challenges

### ISSUE THREAD

**Issue by ghost** [CCV-GFSU/Events#1]
# Title
Serverless Architecture Security  Challenges
## Abstract

1. Workings of serverless architecture 
2. Security drawbacks in serverless architecture
3. Attacks on serverless architecture

## Time
20-25 mins

## Link to Slides/Content/References
https://martinfowler.com/articles/serverless.html
https://www.puresec.io/hubfs/SAS-Top10-2018/PureSec%20-%20SAS%20Top%2010%20-%202018.pdf
## About Yourself
Vinay Gujar - DFIS-GFSU

**Comment by gaurav-gogia** [comment]
Looks good. Please provide a link to your content.

**Comment by Tanster221** [comment]
Sounds good looking forward to your session.
