### ISSUE TITLE
Threat Hunting with Splunk

### ISSUE THREAD

**Issue by ghost** [CCV-GFSU/Events#2]
Title : Threat Hunting with Splunk

Abstract

- Threat hunting is the proactive search for cyber threats in the network environment

- Splunk helps you to aggregate the threats and see them in real time

- This helps discovering APT (Advanced Persistent Threats) prior to any damage done to the enterprise environment.

Time : 30 mins

Link to Slides/Content/References

https://www.splunk.com/en_us/resources/videos/splunk-for-security-investigation-threat-detection.html

https://www.cybereason.com/blog/blog-the-eight-steps-to-threat-hunting

https://blog.augustschell.com/3-tips-for-threat-hunting-with-splunk

About us

VInay Gujar & Ronak Bhatt, DFIS-GFSU

**Comment by gaurav-gogia** [comment]
Looks good. Thanks 😊
