### ISSUE TITLE
Bug Bounty - Life of a Pentester

### ISSUE THREAD

**Issue by CyberHacky-zz** [CCV-GFSU/Events#3]
Bug Bounty - Method to Secure Services

## Abstract

A bug bounty program, also called a vulnerability rewards program (VRP), is a crowdsourcing initiative that rewards individuals for discovering and reporting software bugs. Bug bounty programs are often initiated to supplement internal code audits and penetration tests as part of an organization's vulnerability management strategy.

## Time
09/07/2019, After 12 PM

## Special Requirements
Passion for Learn about it, :)

## Link to Slides/Content/References
https://www.hackerone.com/resources/bug-bounty-basics
https://forum.bugcrowd.com/

## About Yourself
Dharmin Suthar
Cyber Security Analyst & Researcher
CEH, CEI, CEISH, CPT, CCSE
Email : suthardharmin@gmail.com

**Comment by gaurav-gogia** [comment]
Thanks. Looking forward to your session :)

**Comment by gaurav-gogia** [comment]
Thanks for the talk :)
