### ISSUE TITLE
Aspect of programing and designing in cyber security.

### ISSUE THREAD

**Issue by htarpara** [CCV-GFSU/Events#5]
# Cyber Security by Design

## points to be covered
Why design is important in cyber security?
Impact of good design 
Why Cyber security community is continuously starving for new mechanism and design?
Questions...

## board & marker

**Comment by gaurav-gogia** [comment]
@htarpara, please provide description of the talk in description section. 

Thanks 🙂

**Comment by htarpara** [comment]
@gaurav-gogia when and where I have to deliver this session? 
Kindly let me know the schedule, so it would be easier for me to be there.

**Comment by gaurav-gogia** [comment]
@htarpara, Schedule is not confirmed at the moment. You'll be informed about it as soon as we get the confirmation. Regardless of the schedule and time, everyone including audience would want a description of the session. Please provide one at your earliest convenience.
